config/routes.rb
Rails.application.routes.draw do
  
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root to: 'index#index'
  
  resources :quotes
  resources :employee_lists
  resources :building_details
  resources :elevators
  resources :batteries
  resources :columns
  resources :buildings
  resources :customers
  resources :addresses
  resources :leads
  resources :messages
  resources :googlemaps

  get '/test', to: 'messages#patate'
  get 'termsAndConditions', to: 'index#termsAndConditions', as: "termsAndConditions"
  get 'privacy', to: 'index#privacy', as: "privacy"
  get 'commercial', to: 'index#commercialpage', as: "commercial"
  get 'residential', to: 'index#residentialpage', as: "residential"
  get 'index', to: 'index#index'
  post 'lead', to: 'leads#create', as: "leadcreate"
  get 'googlemap', to: 'googlemaps#index', as: "maps"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :access, :rails_admin
      can :manage, :all
    else
      cannot :read, :admin
    end
   
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/address.rb
class Address < ApplicationRecord
    has_many :buildings
    has_many :customers
end

app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    has_many :columns
    belongs_to :employee
end

app/models/building.rb
class Building < ApplicationRecord
    belongs_to :customer
    belongs_to :address
    has_many :building_details
    has_many :batteries
end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord
    belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery
    has_many :elevators
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :user
    belongs_to :address
    has_many :buildings
   
end

app/models/dim_customer.rb
class DimCustomer < SecondBase::Base
end

app/models/elevator.rb
require 'slack-notifier'
class Elevator < ApplicationRecord
    belongs_to :column
    after_update :twilio
    after_update :hello

    def hello
        puts '---------------'
        puts 'hello'
        puts '---------------'

        notifier = Slack::Notifier.new ENV['slack_key']
        notifier.ping "The Elevator #{id} with Serial Number #{serial_number} changed status from #{status_before_last_save} to #{status} "
    end    

    # def do_something
    #     puts '------does it work ?------'
    #     ENV['slack_key']
    #     notifier = Slack::Notifier.new "https://hooks.slack.com/services/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L"
    #     notifier.ping "Hello World"
    # end  
    
    def twilio
        if @elevator_status_changed == "Intervention" then 
            
          account_sid = ENV['TWILIO_ACCOUNT_SID']
          auth_token = ENV['TWILIO_AUTH_TOKEN']
          @client = Twilio::REST::Client.new(account_sid, auth_token)
  
          message = @client.messages.create(
              to: '+14186557999',
              from: '+15203416848',
              body: "The status from elevator #{id} in building #{column.battery.building.id} has changed from #{status_before_last_save} to #{status}."
          )
        end
    end
end
 

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
    has_many :batteries
end

app/models/fact_contact.rb
class FactContact < SecondBase::Base
end

app/models/fact_elevator.rb
class FactElevator < SecondBase::Base
end

app/models/fact_quote.rb
class FactQuote < SecondBase::Base
end

app/models/lead.rb
class Lead < ApplicationRecord
    
end

app/models/quote.rb
class Quote < ApplicationRecord
 
end

app/models/stat.rb
class Stat < SecondBase::Base
end

app/models/user.rb
class User < ApplicationRecord
  has_one :customer
  has_one :employee
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: %i[ show edit update destroy ]

  # GET /buildings or /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1 or /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings or /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to building_url(@building), notice: "Building was successfully created." }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to building_url(@building), notice: "Building was successfully updated." }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url, notice: "Building was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:number_and_street, :building_administrator_full_name, :building_administrator_email, :building_administrator_phone, :building_technical_contact_full_name, :building_technical_contact_email, :building_technical_contact_phone)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/buildings/_form.html.erb
<%= form_with(model: building, local: true) do |form| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number_and_street %>
    <%= form.text_field :number_and_street %>
  </div>

  <div class="field">
    <%= form.label :building_administrator_full_name %>
    <%= form.text_field :building_administrator_full_name %>
  </div>

  <div class="field">
    <%= form.label :building_administrator_email %>
    <%= form.text_field :building_administrator_email %>
  </div>

  <div class="field">
    <%= form.label :building_administrator_phone %>
    <%= form.text_field :building_administrator_phone %>
  </div>

  <div class="field">
    <%= form.label :building_technical_contact_full_name %>
    <%= form.text_field :building_technical_contact_full_name %>
  </div>

  <div class="field">
    <%= form.label :building_technical_contact_email %>
    <%= form.text_field :building_technical_contact_email %>
  </div>

  <div class="field">
    <%= form.label :building_technical_contact_phone %>
    <%= form.text_field :building_technical_contact_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Number and street</th>
      <th>Building administrator full name</th>
      <th>Building administrator email</th>
      <th>Building administrator phone</th>
      <th>Building technical contact full name</th>
      <th>Building technical contact email</th>
      <th>Building technical contact phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.number_and_street %></td>
        <td><%= building.building_administrator_full_name %></td>
        <td><%= building.building_administrator_email %></td>
        <td><%= building.building_administrator_phone %></td>
        <td><%= building.building_technical_contact_full_name %></td>
        <td><%= building.building_technical_contact_email %></td>
        <td><%= building.building_technical_contact_phone %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number and street:</strong>
  <%= @building.number_and_street %>
</p>

<p>
  <strong>Building administrator full name:</strong>
  <%= @building.building_administrator_full_name %>
</p>

<p>
  <strong>Building administrator email:</strong>
  <%= @building.building_administrator_email %>
</p>

<p>
  <strong>Building administrator phone:</strong>
  <%= @building.building_administrator_phone %>
</p>

<p>
  <strong>Building technical contact full name:</strong>
  <%= @building.building_technical_contact_full_name %>
</p>

<p>
  <strong>Building technical contact email:</strong>
  <%= @building.building_technical_contact_email %>
</p>

<p>
  <strong>Building technical contact phone:</strong>
  <%= @building.building_technical_contact_phone %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>